### ISSUE TITLE
tkinter issue in requirements.txt

### ISSUE THREAD

**Issue by RandomInternetPreson** [tegridydev/auto-md#1]
Thank you for this project :3 I've tested it on my repos and it works really well.

One issue I had while installing was "tkinter" in the requirements file needed to be changed to "tk" 

I have your code running in a python 3.11 miniconda environment on Ubuntu.  I cloned the repo instead of downloading the .zip.

**Comment by BlaisePx** [comment]
Can confirm tkinter needed to be changed to tk in requirements.txt

**Comment by tegridydev** [comment]
Appreciate the feedback and issue identification + fix! @RandomInternetPreson @BlaisePx 

Pushing out a complete refactor updated codebase shortly x
